config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :grievances

  root 'grievances#index'
  get '/cities/(:state)', to: 'application#cities'
  get '/cops/search', to: 'application#cops'
  patch '/cops/new', to: 'application#cops_create', as: :create_cop
  get '/connected-grievances/search', to: 'application#connected_grievances'
  get '/my-grievances/(:page)', to: 'grievances#my_grievances', as: :my_grievances
  get '/new-grievances/(:page)', to: 'grievances#new_grievances', as: :new_grievances
  get '/changed-grievances/(:page)', to: 'grievances#changed_grievances', as: :changed_grievances
  get '/search', to: 'grievances#search', as: :search
  get '/grievances/:id/approve', to: 'grievances#approve', as: :approve_grievance
  get '/grievances/:id/disapprove', to: 'grievances#disapprove', as: :disapprove_grievance

end

app/models/grievance.rb
class Grievance < ActiveRecord::Base
  belongs_to :state
  belongs_to :city
  belongs_to :cop
  belongs_to :user
  belongs_to :revision, class_name: "Grievance", foreign_key: "revision_id"
  has_many :connected_grievance_associations
  has_many :connected_grievances, through: :connected_grievance_associations, source: "connected"

  validates_presence_of :city_name, :state_name, :cop_id, :date_incident, :title, :description, :user

  scope :visible, -> (user) do 
    result = where(is_revision: false)
    if user.present?
      if user.is_admin
        result
      else
        result.where("(visible = 'true') OR (user_id = ?)", user.id)
      end
    else
      result.where(visible: true)
    end
  end

  attr_accessor :connected_grievances_ids
  attr_accessor :cop_badge
  attr_accessor :cop_race

  after_initialize :default_values
  before_save :generate_text_search
  before_save :extract_names

  private

  def default_values
    self.date_incident ||= Date.today
    self.connected_grievances_ids ||= self.connected_grievances.pluck(:id).join(",")
  end

  def generate_text_search
    text_search = []
    text_search << self.id
    text_search << self.title
    text_search << self.description
    text_search << self.cop.try(:name)
    text_search << self.cop.try(:badge_number)
    text_search << self.state.try(:name)
    text_search << self.city.try(:name)
    text_search << self.date_incident.strftime("%m/%d/%Y")
    self.text_search = I18n.transliterate(text_search.join(" ")).upcase.gsub(/[^0-9A-Z ]/, "")
  end

  def extract_names
    self.cop_name = self.cop.try(:name) || ""
    self.city_name = self.city.try(:name) || ""
    self.state_name = self.state.try(:name) || ""
  end
end

app/controllers/grievances_controller.rb
class GrievancesController < ApplicationController
  before_action :set_grievance, only: [:show, :edit, :update, :destroy, :approve, :disapprove]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  before_action :check_ownership, only: [:edit, :update, :destroy]
  before_action :check_admin, only: [:new_grievances, :changed_grievances, :approve, :disapprove]

  # GET /grievances
  # GET /grievances.json
  def index
    @title = "All Grievances"
    @grievances = Grievance.visible(current_user).order(date_incident: :desc).paginate(:page => params[:page], :per_page => 20)
  end

  def my_grievances
    @title = "My Grievances"
    @grievances = current_user.grievances.where.not(is_revision: true).order(date_incident: :desc).paginate(:page => params[:page], :per_page => 20)
    render :index
  end

  def new_grievances
    @title = "New grievances waiting for approval"
    @grievances = Grievance.where(is_new: true).order(date_incident: :desc).paginate(:page => params[:page], :per_page => 20)
    render :index
  end

  def changed_grievances
    @title = "Changed grievances waiting for approval"
    @grievances = Grievance.where(is_revision: false).where.not(revision: nil).order(date_incident: :desc).paginate(:page => params[:page], :per_page => 20)
    render :index
  end

  def search
    @title = "Filtered Grievances"
    @cop = params[:cop].present? ? Cop.find_by(id: params[:cop]) : nil
    q = I18n.transliterate(params[:q]).upcase.gsub(/[^0-9A-Z ]/, "") if params[:q].present?
    @grievances = Grievance.visible(current_user)
    @grievances = @grievances.where(state_name: params[:state]) if params[:state].present?
    @grievances = @grievances.where(city_name: params[:city]) if params[:city].present?
    @grievances = @grievances.where(cop_id: params[:cop]) if params[:cop].present?
    @grievances = @grievances.where("text_search LIKE ?", "%#{q}%") if params[:q].present?
    @grievances = @grievances.order(date_incident: :desc).paginate(:page => params[:page], :per_page => 20)
    render :index
  end

  # GET /grievances/1
  # GET /grievances/1.json
  def show
  end

  # GET /grievances/new
  def new
    @grievance = Grievance.new
  end

  # GET /grievances/1/edit
  def edit
    if @grievance.revision.present?
      @original = @grievance 
      @grievance = @grievance.revision
    end
  end

  def approve
    if @grievance.is_new
      @grievance.update_attributes!(is_new: false, visible: true)
      redirect_to new_grievances_path, notice: "Grievance ##{@grievance.id} approved. Now it is visible."
    elsif @grievance.revision.present?
      @revision = @grievance.revision

      # erase actual grievance
      original_id = @grievance.id
      @grievance.connected_grievances.clear
      @grievance.delete

      # change revision id to the original id
      ConnectedGrievanceAssociation.where(grievance_id: @revision.id).each do |cg| 
        cg.update_attributes(grievance_id: original_id)
      end
      @revision.update_attributes(visible: true, is_new: false, is_revision: false, id: original_id)

      redirect_to changed_grievances_path, notice: "Changes to grievance ##{@grievance.id} approved."
    end
  end

  def disapprove
    if @grievance.revision.present?
      @grievance.revision.connected_grievances.clear
      @grievance.revision.delete
      redirect_to grievances_path, notice: "Changes to grievance ##{@grievance.id} disapproved."
    end
  end

  # POST /grievances
  # POST /grievances.json
  def create
    @grievance = Grievance.new(grievance_params, is_revision: false, visible: false, is_new: true)

    @grievance.connected_grievances.clear
    params[:grievance][:connected_grievances_ids].split(',').each do |id|
      grievance = Grievance.find_by(id: id)
      @grievance.connected_grievances << grievance if grievance.present?
    end

    respond_to do |format|
      if @grievance.save
        format.html { redirect_to grievances_path, notice: "Your grievance ##{@grievance.id} will be visible after approval." }
        format.json { render :show, status: :created, location: @grievance }
      else
        format.html { render :new }
        format.json { render json: @grievance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grievances/1
  # PATCH/PUT /grievances/1.json
  def update
    # check if we're editing a pending revision, delete current revision
    @grievance = Grievance.find_by(revision: @grievance) if @grievance.is_revision 
    @grievance.revision.delete if @grievance.revision.present? # overwrite pending revision

    # create a new revision and associates it to grievance
    @revision = Grievance.create(grievance_params.merge({ visible: false, is_revision: true, is_new: false }))
    @grievance.update_attributes(revision: @revision)

    # connected grievances
    @revision.connected_grievances.clear
    params[:grievance][:connected_grievances_ids].split(',').each do |id|
      grievance = Grievance.find_by(id: id)
      @revision.connected_grievances << grievance if grievance.present?
    end
    @revision.save

    # render
    respond_to do |format|
      if @grievance.errors.empty?
        format.html { redirect_to root_path, notice: "Your changes in grievance ##{@grievance.id} will be visible after approval." }
        format.json { render :show, status: :ok, location: @grievance }
      else
        format.html { render :edit }
        format.json { render json: @grievance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grievances/1
  # DELETE /grievances/1.json
  def destroy
    @grievance.destroy
    respond_to do |format|
      format.html { redirect_to grievances_url, notice: 'Grievance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def check_ownership
      if ! user_signed_in?
        redirect_to :root, alert: "You need to be logged to do that"
      elsif (@grievance.user != current_user) && ! current_user.is_admin
        redirect_to :root, alert: "You aren't the owner of this grievance"
      end
    end

    def check_admin
      unless user_signed_in? && current_user.is_admin
        redirect_to :root, alert: "Unauthorized access!"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_grievance
      @grievance = Grievance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grievance_params
      result = params.require(:grievance).permit(:cop_id, :date_incident, :description, :user_id, :publish_user_race, :publish_user_age, :cop_name, :cop_race, :cop_badge, :state_name, :city_name, :title, :connected_grievances_ids)
      result[:user] = current_user

      # "unpack" some params
      state = nil
      city = nil
      cop = nil

      state = State.find_by(name: params[:grievance][:state_name])
      if state.blank?
        if CS.states(:us).keys.include?(params[:grievance][:state_name].to_sym)
          state = State.create(name: params[:grievance][:state_name])
        else
          # isn't a real state
          if params[:grievance][:state_name].present?
            raise "Invalid State"
          end
        end
      end

      if state.present?
        city = City.find_by(state: state, name: params[:grievance][:city_name])
        if city.blank?
          if CS.cities(state.name, :us).include?(params[:grievance][:city_name])
            city = City.create(state: state, name: params[:grievance][:city_name])
          else
            # isn't a real city
            if params[:grievance][:city_name].present?
              raise "Invalid City"
            end
          end
        end
      end

      if state.present? && city.present?
        cop = Cop.find_by(id: params[:grievance][:cop_id])
        if cop.blank?
          # create new cop
          if params[:grievance][:cop_name].present?
            cop = Cop.create(state: state, city: city, name: params[:grievance][:cop_name], badge_number: params[:grievance][:cop_badge], race: params[:grievance][:cop_race])
          end
        end
      end

      result[:cop_id] = cop.try(:id)
      result[:city_id] = city.try(:id)
      result[:city_name] = city.try(:name)
      result[:state_id] = state.try(:id)
      result[:state_name] = state.try(:name)

      result
    end
end

app/helpers/grievances_helper.rb
module GrievancesHelper
end

app/views/grievances/_form.html.erb
<% 
  # novo? descobrimos cidade e estado
  if @grievance.id.nil?
    location = GeoIP.new('db/GeoLiteCity.dat').city(request.remote_ip)
    if location.try(:country_code2) == "US"
      @grievance.state_name = location.region_name
      @grievance.city_name = location.city_name
    else
      @grievance.state_name = "CA"
      @grievance.city_name = "San Francisco"
    end
  end
%>

<%= simple_form_for @grievance do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-md-2">
      <%= f.input :id, label: "Code #", readonly: true %>
    </div>
    <div class="col-md-2">
      <%= f.input :state_name, collection: CS.states(:us).map { |k,v| ["#{k} - #{v}", k] }, prompt: "-- Select a State", label: "State" %>
    </div>
    <div class="col-md-2">
      <%= f.input :city_name, collection: CS.cities(@grievance.state_name, :us), prompt: @grievance.state_name.blank? ? "-- Select a State First --" : "-- Select a City --", label: "City" %>
    </div>
    <div class="col-md-2">
      <%= f.input :date_incident, as: :string, input_html: { class: "date", placeholder: "mm/dd/yyyy", value: @grievance.date_incident.strftime("%m/%d/%Y") }, label: "Incident Date" %>
    </div>
    <div class="col-md-4">
      <%= f.input :cop_id, label: "Cop (name / badge number)", input_html: { data: { name: @grievance.cop.try(:name) || "", badge: @grievance.cop.try(:badge_number) || "" } } %>
      <input type="hidden" name="grievance[cop_name]" value="">
      <input type="hidden" name="grievance[cop_badge]" value="">
      <input type="hidden" name="grievance[cop_race]" value="">
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.input :title, label: "Incident Title (be succinct - try to use about 3 words)" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.input :description, label: "Incident Description", input_html: {rows: 7} %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.input :connected_grievances_ids, label: "Connected Grievances", input_html: { data: { info: @grievance.connected_grievances.map { |g| { id: g.id, title: g.title } }.to_json } } %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= f.input :publish_user_race %>
    </div>
    <div class="col-md-2">
      <%= f.input :publish_user_age %>
    </div>
  </div>

  <br>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            grievances_path, :class => 'btn btn-default' %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

<a data-target="#new-cop" data-toggle="modal" class="hide" id="btn-new-cop"></a>

<div id="new-cop" class="modal fade" tabindex="-1" data-width="100">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="<%= create_cop_path %>" id="form-cop">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">New Cop</h4>
      </div>

      <div class="modal-body">
        <div class="row">
          <div class="col-md-4 element-group">
            <label class="control-label" for="cop_name">
              <span class="title">Name</span>
            </label>
            <p>
              <input class="form-control" type="text" id="cop-name" name="cop[name]">
            </p>
            <p>
              <span class="help-block"></span>
            </p>
          </div>
          <!--/col-md-4-->

          <div class="col-md-4 element-group">
            <label class="control-label" for="cop_badge">
              <span class="title">Badge Number</span>
            </label>
            <p>
              <input class="form-control" type="text" id="cop-badge" name="cop[badge]">
            </p>
            <p>
              <span class="help-block"></span>
            </p>
          </div>
          <!--/col-md-4-->

          <div class="col-md-4 element-group">
            <label class="control-label" for="cop_race">
              <span class="title">Cop Ethnicy</span>
            </label>
            <p>
              <select class="form-control" type="text" id="cop-race" name="cop[race]">
                <option value="Asian">Asian</option>
                <option value="Black">Black</option>
                <option value="Latino">Latino</option>
                <option value="White">White</option>
                <option value="">I don't know</option>
              </select>
            </p>
            <p>
              <span class="help-block"></span>
            </p>
          </div>
          <!--/col-md-4-->
        </div>
        <!--/row-->
      </div>

      <div class="modal-footer">
        <button type="button" data-dismiss="modal" id="btn-cancel-cop" class="btn btn-default">Cancel</button>
        <button type="submit" class="btn btn-primary" id="btn-save-cop">Create Cop</button>
      </div>
      </form>
    </div>
  </div>
</div>

app/views/grievances/edit.html.erb
<div class="alert alert-dismissible alert-info" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  Your changes will be visible after approval.
</div>

<div class="page-header">
  <h1>Edit Grievance #<%= @original.present? ? @original.id : @grievance.id %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grievances/index.html.erb
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<div class="row">
  <div class="col-md-1">
    <div class="form-group">
      <%= link_to "New", new_grievance_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <form role="search" action="<%= search_path %>" method="get">
    <div class="col-md-2">
      <div class="form-group">
        <select class="form-control" type="text" id="filter-state" name="state">
          <option value="">-- All States --</option>
          <% CS.states(:us).each do |k, state| %>
            <option value="<%= k %>" <%= params[:state] == k.to_s ? "selected" : "" %>><%= "#{k} - #{state}" %></option>
          <% end %>
        </select>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <select class="form-control" type="text" id="filter-city" name="city">
        <option value="">-- All Cities --</option>
        <% if params[:state].present? %>
          <% CS.cities(params[:state], :us).each do |city| %>
            <option value="<%= city %>" <%= params[:city] == city.to_s ? "selected" : "" %>><%= city %></option>
          <% end %>
        <% end %>
      </select>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <input class="form-control" type="text" id="filter-cop" name="cop" data-name="<%= @cop.try(:name) || "" %>" data-badge="<%= @cop.try(:badge_number) || "" %>" value="<%= params[:cop] %>">
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-search"></i></span>
          <input class="form-control" type="text" id="filter-text" name="q" placeholder="Search" value="<%= params[:q] %>">
        </div>
      </div>
    </div>
    <div class="col-md-1">
      <button type="submit" class="btn btn-default">Filter!</button>
    </div>
  </form>

</div>

<table class="table table-striped" id="grievance-table">
  <thead>
    <tr>
      <th><strong>#</strong></th>
      <th>Date</th>
      <th>City</th>
      <th>Cop</th>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @grievances.each do |grievance| %>
      <tr data-show-path="<%= grievance_path(grievance) %>">
        <td><%= grievance.id %> <%= grievance.visible? ? "" : "<span class='label label-warning' data-toggle='tooltip' data-placement='left' title='Created, waiting for approval'>*</span>".html_safe %> <%= grievance.revision.blank? ? "" : "<span class='label label-danger' data-toggle='tooltip' data-placement='left' title='Changed, waiting for approval'>*</span>".html_safe %></td>
        <td><%= grievance.date_incident %></td>
        <td><%= "#{grievance.state.try(:name)} - #{grievance.city.try(:name)}" %></td>
        <td><%= "#{grievance.cop.try(:badge_number)} - #{grievance.cop.try(:name)}" %></td>
        <td><%= [grievance.publish_user_age ? grievance.user.age : "---", grievance.publish_user_race ? grievance.user.race : "---"].join(" / ") %></td>
        <td><%= grievance.title %></td>
        <td><%= grievance.description.truncate(20) %></td>
        <td>
          <%= link_to "View", grievance_path(grievance), class: "btn btn-default btn-xs" %>
          <% if user_signed_in? && (current_user.is_admin || current_user == grievance.user) %>
          <%= link_to "Edit", edit_grievance_path(grievance), class: "btn btn-default btn-xs" %>
          <%= link_to "Delete", grievance_path(grievance), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @grievances, renderer: BootstrapPagination::Rails %>

app/views/grievances/new.html.erb
<div class="page-header">
  <h1>New Grievance</h1>
</div>
<%= render :partial => 'form' %>

app/views/grievances/show.html.erb
<% if @grievance.is_new %>
<div class="alert alert-dismissible alert-warning" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  This new grievance is pending approval.
</div>
<% end %>

<% if @grievance.revision.present? %>
<div class="alert alert-dismissible alert-warning" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  This grievance have a pending approval revision.
</div>
<% end %>

<div class="page-header">
  <h1>Showing Grievance #<%= @grievance.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Incident Date:</strong></dt>
  <dd><%= @grievance.date_incident.strftime("%m/%d/%Y") %></dd>
  <dt><strong>City:</strong></dt>
  <dd><%= "#{link_to @grievance.city.name, search_path(state: @grievance.state.name, city: @grievance.city.name)}, #{link_to @grievance.state.name, search_path(state: @grievance.state.name)}".html_safe %></dd>
  <dt><strong>Cop:</strong></dt>
  <dd><%= link_to "#{@grievance.cop.badge_number} - #{@grievance.cop.name} (#{@grievance.cop.race}), from #{@grievance.cop.city.name}, #{@grievance.cop.state.name}", search_path(cop: @grievance.cop.id) %></dd>
  <dt><strong>Title:</strong></dt>
  <dd><%= @grievance.title %></dd>
  <dt><strong>Description:</strong></dt>
  <dd><%= @grievance.description %></dd>
  <dt><strong>User:</strong></dt>
  <% if current_user.is_admin %>
  <dd><%= "#{@grievance.user.name} (#{@grievance.user.email}), #{@grievance.user.age}, #{@grievance.user.race}" %></dd>
  <% else %>
  <dd><%= [@grievance.publish_user_age ? @grievance.user.age : "---", @grievance.publish_user_race ? @grievance.user.race : "---"].join(" / ") %></dd>
  <% end %>
  <dt><strong>Connected Grievances:</strong></dt>
    <% @grievance.connected_grievances.each do |grievance| %>
    <dd>
      <%= link_to "##{grievance.id} - #{grievance.title} (#{grievance.city.name}, #{grievance.state.name}), on #{grievance.date_incident.strftime("%m/%d/%Y")}", grievance_path(grievance) %>
    </dd>
    <% end %>
</dl>

<% if @grievance.revision.present? && user_signed_in? && (current_user.is_admin || (current_user == @grievance.user)) %>
<br>
<dl class="dl-horizontal">
  <h3>Pending Changes</h3>
  <dt><strong>Incident Date:</strong></dt>
  <dd><%= @grievance.revision.date_incident.strftime("%m/%d/%Y") %></dd>
  <dt><strong>City:</strong></dt>
  <dd><%= "#{link_to @grievance.revision.city.name, search_path(state: @grievance.revision.state.name, city: @grievance.revision.city.name)}, #{link_to @grievance.revision.state.name, search_path(state: @grievance.revision.state.name)}".html_safe %></dd>
  <dt><strong>Cop:</strong></dt>
  <dd><%= link_to "#{@grievance.revision.cop.badge_number} - #{@grievance.revision.cop.name} (#{@grievance.revision.cop.race}), from #{@grievance.revision.cop.city.name}, #{@grievance.revision.cop.state.name}", search_path(cop: @grievance.revision.cop.id) %></dd>
  <dt><strong>Title:</strong></dt>
  <dd><%= @grievance.revision.title %></dd>
  <dt><strong>Description:</strong></dt>
  <dd><%= @grievance.revision.description %></dd>
  <dt><strong>User:</strong></dt>
  <% if current_user.is_admin %>
  <dd><%= "#{@grievance.revision.user.name} (#{@grievance.revision.user.email}), #{@grievance.revision.user.age}, #{@grievance.revision.user.race}" %></dd>
  <% else %>
  <dd><%= [@grievance.revision.publish_user_age ? @grievance.revision.user.age : "---", @grievance.revision.publish_user_race ? @grievance.revision.user.race : "---"].join(" / ") %></dd>
  <% end %>
  <dt><strong>Connected Grievances:</strong></dt>
    <% @grievance.revision.connected_grievances.each do |grievance| %>
    <dd>
      <%= link_to "##{grievance.id} - #{grievance.title} (#{grievance.city.name}, #{grievance.state.name}), on #{grievance.date_incident.strftime("%m/%d/%Y")}", grievance_path(grievance) %>
    </dd>
    <% end %>
</dl>  
<% end %>

<br>

<%= link_to "Cancel", grievances_path, class: "btn btn-default" %>
<% if user_signed_in? && (current_user.is_admin || current_user == @grievance.user) %>
<%= link_to "Edit", edit_grievance_path(@grievance), class: "btn btn-default" %>
<%= link_to "Delete", grievance_path(@grievance), class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
<% if current_user.is_admin && (@grievance.is_new || @grievance.revision.present?) %>
<%= link_to "Approve", approve_grievance_path(@grievance), class: "btn btn-primary" %>
<% if @grievance.revision.present? %>
<%= link_to "Disapprove", disapprove_grievance_path(@grievance), class: "btn btn-default" %>
<% end %>
<% end %>
<% end %>